/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'bg-base': 'var(--bg-base)',
        'bg-surface': 'var(--bg-surface)',
        'bg-elevated': 'var(--bg-elevated)',
        'border-subtle': 'var(--border-subtle)',
        'border-default': 'var(--border-default)',
        'border-strong': 'var(--border-strong)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-tertiary': 'var(--text-tertiary)',
        'text-disabled': 'var(--text-disabled)',
        'accent': 'var(--accent)',
        'accent-subtle': 'var(--accent-subtle)',
        'success': 'var(--success)',
        'success-subtle': 'var(--success-subtle)',
        'warning': 'var(--warning)',
        'warning-subtle': 'var(--warning-subtle)',
        'danger': 'var(--danger)',
        'danger-subtle': 'var(--danger-subtle)',
        'info': 'var(--info)',
        'info-subtle': 'var(--info-subtle)',
        "surface-container-low": "#1b1b1d",
        "on-primary-container": "#eeefff",
        "outline-variant": "#434655",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-fixed": "#360f00",
        "on-secondary": "#182d63",
        "primary-container": "#2563eb",
        "on-background": "#e5e1e4",
        "error-container": "#93000a",
        "secondary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed": "#ffdbcd",
        "inverse-surface": "#e5e1e4",
        "surface-container-highest": "#353437",
        "primary": "#b4c5ff",
        "outline": "#8d90a0",
        "surface-container-high": "#2a2a2c",
        "surface-container": "#201f21",
        "secondary-container": "#33467e",
        "on-error": "#690005",
        "background": "#131315",
        "error": "#ffb4ab",
        "surface-dim": "#131315",
        "surface": "#131315",
        "surface-tint": "#b4c5ff",
        "inverse-on-surface": "#313032",
        "on-secondary-fixed": "#00174b",
        "on-surface": "#e5e1e4",
        "on-primary-fixed": "#00174b",
        "on-primary": "#002a78",
        "on-secondary-container": "#a4b6f5",
        "surface-container-lowest": "#0e0e10",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#31447b",
        "on-tertiary-container": "#ffede6",
        "on-tertiary": "#581e00",
        "tertiary-fixed-dim": "#ffb596",
        "inverse-primary": "#0053db",
        "on-surface-variant": "#c3c6d7",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-variant": "#353437",
        "tertiary": "#ffb596",
        "tertiary-container": "#bc4800",
        "secondary": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "surface-bright": "#39393b",
        "primary-fixed": "#dbe1ff"
      },
      fontFamily: {
        display: ["Instrument Serif", "serif"],
        headline: ["Instrument Serif", "serif"],
        sans: ["Inter", "sans-serif"],
        ui: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"]
      },
      borderRadius: {
        "sm": "0.375rem",
        "DEFAULT": "0.5rem",
        "md": "0.625rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      animation: {
        'shimmer': 'shimmer 1.6s ease-in-out infinite',
        'breathe-dot': 'breatheDot 2s ease-in-out infinite',
        'count-up': 'countUp 0.6s ease-out forwards',
        'slide-right': 'slideRight 0.22s cubic-bezier(0.16, 1, 0.3, 1) forwards',
        'fade-in': 'fadeIn 0.28s cubic-bezier(0.16, 1, 0.3, 1) forwards',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        breatheDot: {
          '0%, 100%': { opacity: '0.6', transform: 'scale(1)' },
          '50%': { opacity: '1', transform: 'scale(1.25)' },
        },
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideRight: {
          '0%': { opacity: '0', transform: 'translateX(40px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
      },
      transitionTimingFunction: {
        'spring': 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      boxShadow: {
        'glass': '0 4px 24px rgba(0,0,0,0.15), inset 0 1px 0 rgba(255,255,255,0.05)',
        'glass-sm': '0 2px 12px rgba(0,0,0,0.10)',
        'glass-modal': '0 24px 64px rgba(0,0,0,0.35)',
      },
    },
  },
  plugins: [],
};
